# -*- coding: utf-8 -*-
"""Student Performance Analysis project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j7xzJ4THes21MynsyiJ4IL2RbdC7RrqS
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/students.csv")

print(df.head())

# 1️⃣ Average marks per subject
print("Average marks in Maths:", df['Maths'].mean())
print("Average marks in English:", df['English'].mean())
print("Average marks in Science:",df['Science'].mean())

# 2️⃣ Highest scorer in each subject
print("Top scorer in Maths:", df.loc[df['Maths'].idxmax(), 'Name'])
print("Top scorer in English:",df.loc[df['English'].idxmax(),'Name'])
print("Top scorer in Science:",df.loc[df['Science'].idxmax(),'Name'])

# 3️⃣ Correlation between StudyHours and total marks
df['TotalMarks'] = df['Maths'] + df['Science'] + df['English']
correlation = df['StudyHours'].corr(df['TotalMarks'])
print("Correlation between Study Hours and Total Marks:", correlation)

# 1️⃣ Bar chart of average marks per subject
subjects = ['Maths', 'Science', 'English']
averages = [df['Maths'].mean(), df['Science'].mean(), df['English'].mean()]

plt.figure(figsize=(8,5))
plt.bar(subjects, averages, color=['blue','green','orange'])
plt.title("Average Marks per Subject")
plt.ylabel("Marks")
plt.show()

# 2️⃣ Scatter plot: Study Hours vs Total Marks
plt.figure(figsize=(8,5))
plt.scatter(df['StudyHours'], df['TotalMarks'], color='red', s=100)
plt.title("Study Hours vs Total Marks")
plt.xlabel("Study Hours")
plt.ylabel("Total Marks")
plt.grid(True)
plt.show()

# 1️⃣ Student with highest total marks
top_student = df.loc[df['TotalMarks'].idxmax(), 'Name']
print("Top student overall:", top_student)

# 2️⃣ Student with lowest total marks
low_student = df.loc[df['TotalMarks'].idxmin(), 'Name']
print("Student needing help:", low_student)

# 3️⃣ Top 3 students overall
top3 = df.sort_values(by='TotalMarks', ascending=False).head(3)
print("\nTop 3 students overall:")
print(top3[['Name','TotalMarks']])





